### ISSUE TITLE
Deprecate CharSet in favor of using variant of String/&str?

### ISSUE THREAD

**Issue by Skarlett** [FssAy/random-string#1]
It appears all the functionality built into Charset is already implemented inside of `String`, it seems to make the most sense externally to face the API to standard-lib types.

Likewise, I think GenResult should just be a `String`

**Comment by FssAy** [comment]
Getting rid of the `Charset` and `GenResult` structs along with the `ToCharset` trait was a good idea, but in your PR the `generate` function didn't work as intended.

- The chars weren't pushed into the result string which resulted in returning an empty string.
- `nth` method was surprisingly more efficient, but it was tricky to get the number of characters in string if they were not an ASCII characters and after implementing the count, efficiency dropped drastically.
- Also version of the crate should be changed to 0.3.0 as your changes were breaking the backwards compatibility and the crate wasn't ready to be used in the production.
